// 자동 생성 — web/scripts/build-exercise-catalog.mjs
//
// 출처: free-exercise-db (https://github.com/yuhonas/free-exercise-db), Unlicense
// (퍼블릭 도메인 — 표기 의무는 없으나 출처를 남긴다).
//
// 손으로 고치지 말 것. 큐레이션이 필요하면 CURATED_EXERCISE_CATALOG에 넣는다 —
// 이름이 겹치면 수기 항목이 이긴다.

import type { ExerciseEquipment } from "./catalog";

/** 소문자 이름 → 장비. 장비를 아는 항목만 담는다(미수록 = unknown). */
export const OPEN_EXERCISE_EQUIPMENT: Readonly<Record<string, ExerciseEquipment>> = {
  "3/4 sit-up": "bodyweight",
  "ab crunch machine": "machine",
  "air bike": "bodyweight",
  "alternate hammer curl": "dumbbell",
  "alternate heel touchers": "bodyweight",
  "alternate incline dumbbell curl": "dumbbell",
  "alternating cable shoulder press": "cable",
  "alternating deltoid raise": "dumbbell",
  "anti-gravity press": "barbell",
  "arnold dumbbell press": "dumbbell",
  "around the worlds": "dumbbell",
  "barbell ab rollout": "barbell",
  "barbell ab rollout - on knees": "barbell",
  "barbell bench press - medium grip": "barbell",
  "barbell curls lying against an incline": "barbell",
  "barbell deadlift": "barbell",
  "barbell full squat": "barbell",
  "barbell glute bridge": "barbell",
  "barbell guillotine bench press": "barbell",
  "barbell hack squat": "barbell",
  "barbell hip thrust": "barbell",
  "barbell incline bench press - medium grip": "barbell",
  "barbell incline shoulder raise": "barbell",
  "barbell rear delt row": "barbell",
  "barbell rollout from bench": "barbell",
  "barbell seated calf raise": "barbell",
  "barbell shoulder press": "barbell",
  "barbell shrug": "barbell",
  "barbell shrug behind the back": "barbell",
  "barbell side bend": "barbell",
  "barbell side split squat": "barbell",
  "barbell squat": "barbell",
  "barbell squat to a bench": "barbell",
  "barbell step ups": "barbell",
  "barbell walking lunge": "barbell",
  "bench dips": "bodyweight",
  "bench jump": "bodyweight",
  "bench press - powerlifting": "barbell",
  "bench press with chains": "barbell",
  "bent-arm barbell pullover": "barbell",
  "bent-arm dumbbell pullover": "dumbbell",
  "bent-knee hip raise": "bodyweight",
  "bent over barbell row": "barbell",
  "bent over dumbbell rear delt raise with head on bench": "dumbbell",
  "bent over low-pulley side lateral": "cable",
  "bent over one-arm long bar row": "barbell",
  "bent over two-arm long bar row": "barbell",
  "bent over two-dumbbell row": "dumbbell",
  "bent over two-dumbbell row with palms in": "dumbbell",
  "board press": "barbell",
  "body-up": "bodyweight",
  "body tricep press": "bodyweight",
  "bodyweight flyes": "barbell",
  "bodyweight squat": "bodyweight",
  "bosu ball cable crunch with side bends": "cable",
  "bottoms up": "bodyweight",
  "box squat": "barbell",
  "box squat with bands": "barbell",
  "box squat with chains": "barbell",
  "bradford/rocky presses": "barbell",
  "butt-ups": "bodyweight",
  "butt lift (bridge)": "bodyweight",
  "butterfly": "machine",
  "cable chest press": "cable",
  "cable crossover": "cable",
  "cable crunch": "cable",
  "cable deadlifts": "cable",
  "cable hammer curls - rope attachment": "cable",
  "cable hip adduction": "cable",
  "cable incline pushdown": "cable",
  "cable incline triceps extension": "cable",
  "cable internal rotation": "cable",
  "cable iron cross": "cable",
  "cable judo flip": "cable",
  "cable lying triceps extension": "cable",
  "cable one arm tricep extension": "cable",
  "cable preacher curl": "cable",
  "cable rear delt fly": "cable",
  "cable reverse crunch": "cable",
  "cable rope overhead triceps extension": "cable",
  "cable rope rear-delt rows": "cable",
  "cable russian twists": "cable",
  "cable seated crunch": "cable",
  "cable seated lateral raise": "cable",
  "cable shoulder press": "cable",
  "cable shrugs": "cable",
  "cable wrist curl": "cable",
  "calf-machine shoulder shrug": "machine",
  "calf press": "machine",
  "calf press on the leg press machine": "machine",
  "calf raise on a dumbbell": "dumbbell",
  "car drivers": "barbell",
  "chair squat": "machine",
  "chin-up": "bodyweight",
  "clean deadlift": "barbell",
  "clean pull": "barbell",
  "clean shrug": "barbell",
  "clean and jerk": "barbell",
  "clean and press": "barbell",
  "clean from blocks": "barbell",
  "clock push-up": "bodyweight",
  "close-grip barbell bench press": "barbell",
  "close-grip dumbbell press": "dumbbell",
  "close-grip ez-bar curl with band": "barbell",
  "close-grip ez-bar press": "barbell",
  "close-grip ez bar curl": "barbell",
  "close-grip front lat pulldown": "cable",
  "close-grip push-up off of a dumbbell": "bodyweight",
  "close-grip standing barbell curl": "barbell",
  "cocoons": "bodyweight",
  "concentration curls": "dumbbell",
  "cross-body crunch": "bodyweight",
  "cross body hammer curl": "dumbbell",
  "crunch - hands overhead": "bodyweight",
  "crunch - legs on exercise ball": "bodyweight",
  "crunches": "bodyweight",
  "cuban press": "dumbbell",
  "dead bug": "bodyweight",
  "deadlift with bands": "barbell",
  "deadlift with chains": "barbell",
  "decline barbell bench press": "barbell",
  "decline close-grip bench to skull crusher": "barbell",
  "decline crunch": "bodyweight",
  "decline dumbbell bench press": "dumbbell",
  "decline dumbbell flyes": "dumbbell",
  "decline dumbbell triceps extension": "dumbbell",
  "decline ez bar triceps extension": "barbell",
  "decline oblique crunch": "bodyweight",
  "decline reverse crunch": "bodyweight",
  "decline smith press": "machine",
  "deficit deadlift": "barbell",
  "dip machine": "machine",
  "dips - triceps version": "bodyweight",
  "double leg butt kick": "bodyweight",
  "drag curl": "barbell",
  "dumbbell alternate bicep curl": "dumbbell",
  "dumbbell bench press": "dumbbell",
  "dumbbell bench press with neutral grip": "dumbbell",
  "dumbbell bicep curl": "dumbbell",
  "dumbbell clean": "dumbbell",
  "dumbbell floor press": "dumbbell",
  "dumbbell flyes": "dumbbell",
  "dumbbell incline row": "dumbbell",
  "dumbbell incline shoulder raise": "dumbbell",
  "dumbbell lunges": "dumbbell",
  "dumbbell lying one-arm rear lateral raise": "dumbbell",
  "dumbbell lying pronation": "dumbbell",
  "dumbbell lying rear lateral raise": "dumbbell",
  "dumbbell lying supination": "dumbbell",
  "dumbbell one-arm shoulder press": "dumbbell",
  "dumbbell one-arm triceps extension": "dumbbell",
  "dumbbell one-arm upright row": "dumbbell",
  "dumbbell prone incline curl": "dumbbell",
  "dumbbell raise": "dumbbell",
  "dumbbell rear lunge": "dumbbell",
  "dumbbell scaption": "dumbbell",
  "dumbbell seated box jump": "dumbbell",
  "dumbbell seated one-leg calf raise": "dumbbell",
  "dumbbell shrug": "dumbbell",
  "dumbbell side bend": "dumbbell",
  "dumbbell squat": "dumbbell",
  "dumbbell squat to a bench": "dumbbell",
  "dumbbell step ups": "dumbbell",
  "dumbbell tricep extension -pronated grip": "dumbbell",
  "ez-bar curl": "barbell",
  "ez-bar skullcrusher": "barbell",
  "elbow to knee": "bodyweight",
  "elevated back lunge": "barbell",
  "elevated cable rows": "cable",
  "external rotation": "dumbbell",
  "external rotation with cable": "cable",
  "fast skipping": "bodyweight",
  "finger curls": "barbell",
  "flat bench cable flyes": "cable",
  "flat bench leg pull-in": "bodyweight",
  "flat bench lying leg raise": "bodyweight",
  "flexor incline dumbbell curls": "dumbbell",
  "floor press": "barbell",
  "floor press with chains": "barbell",
  "flutter kicks": "bodyweight",
  "frankenstein squat": "barbell",
  "freehand jump squat": "bodyweight",
  "frog sit-ups": "bodyweight",
  "front barbell squat": "barbell",
  "front barbell squat to a bench": "barbell",
  "front cable raise": "cable",
  "front dumbbell raise": "dumbbell",
  "front incline dumbbell raise": "dumbbell",
  "front raise and pullover": "barbell",
  "front squat (clean grip)": "barbell",
  "front two-dumbbell raise": "dumbbell",
  "full range-of-motion lat pulldown": "cable",
  "glute ham raise": "machine",
  "glute kickback": "bodyweight",
  "good morning": "barbell",
  "good morning off pins": "barbell",
  "gorilla chin/crunch": "bodyweight",
  "hack squat": "machine",
  "hammer curls": "dumbbell",
  "hammer grip incline db bench press": "dumbbell",
  "handstand push-ups": "bodyweight",
  "hang clean": "barbell",
  "hang clean - below the knees": "barbell",
  "hang snatch": "barbell",
  "hang snatch - below knees": "barbell",
  "hanging bar good morning": "barbell",
  "hanging leg raise": "bodyweight",
  "hanging pike": "bodyweight",
  "heaving snatch balance": "barbell",
  "high cable curls": "cable",
  "hyperextensions with no hyperextension bench": "bodyweight",
  "incline barbell triceps extension": "barbell",
  "incline bench pull": "barbell",
  "incline cable chest press": "cable",
  "incline cable flye": "cable",
  "incline dumbbell bench with palms facing in": "dumbbell",
  "incline dumbbell curl": "dumbbell",
  "incline dumbbell flyes": "dumbbell",
  "incline dumbbell flyes - with a twist": "dumbbell",
  "incline hammer curls": "dumbbell",
  "incline inner biceps curl": "dumbbell",
  "incline push-up": "bodyweight",
  "incline push-up close-grip": "bodyweight",
  "incline push-up medium": "bodyweight",
  "incline push-up reverse grip": "bodyweight",
  "incline push-up wide": "bodyweight",
  "iron cross": "dumbbell",
  "isometric chest squeezes": "bodyweight",
  "isometric neck exercise - front and back": "bodyweight",
  "isometric neck exercise - sides": "bodyweight",
  "isometric wipers": "bodyweight",
  "jm press": "barbell",
  "jackknife sit-up": "bodyweight",
  "janda sit-up": "bodyweight",
  "jefferson squats": "barbell",
  "jerk balance": "barbell",
  "jerk dip squat": "barbell",
  "knee tuck jump": "bodyweight",
  "kneeling cable crunch with alternating oblique twists": "cable",
  "kneeling cable triceps extension": "cable",
  "kneeling high pulley row": "cable",
  "kneeling jump squat": "barbell",
  "kneeling single-arm high pulley row": "cable",
  "kneeling squat": "barbell",
  "landmine 180's": "barbell",
  "landmine linear jammer": "barbell",
  "lateral bound": "bodyweight",
  "leg extensions": "machine",
  "leg lift": "bodyweight",
  "leg pull-in": "bodyweight",
  "leverage chest press": "machine",
  "leverage deadlift": "machine",
  "leverage decline chest press": "machine",
  "leverage high row": "machine",
  "leverage incline chest press": "machine",
  "leverage iso row": "machine",
  "leverage shoulder press": "machine",
  "leverage shrug": "machine",
  "low cable crossover": "cable",
  "low cable triceps extension": "cable",
  "low pulley row to neck": "cable",
  "lunge sprint": "machine",
  "lying cable curl": "cable",
  "lying cambered barbell row": "barbell",
  "lying close-grip bar curl on high pulley": "cable",
  "lying close-grip barbell triceps extension behind the head": "barbell",
  "lying close-grip barbell triceps press to chin": "barbell",
  "lying dumbbell tricep extension": "dumbbell",
  "lying high bench barbell curl": "barbell",
  "lying leg curls": "machine",
  "lying machine squat": "machine",
  "lying one-arm lateral raise": "dumbbell",
  "lying rear delt raise": "dumbbell",
  "lying supine dumbbell curl": "dumbbell",
  "lying t-bar row": "machine",
  "lying triceps press": "barbell",
  "machine bench press": "machine",
  "machine bicep curl": "machine",
  "machine preacher curls": "machine",
  "machine shoulder (military) press": "machine",
  "machine triceps extension": "machine",
  "middle back shrug": "dumbbell",
  "muscle snatch": "barbell",
  "narrow stance hack squats": "machine",
  "narrow stance leg press": "machine",
  "narrow stance squats": "barbell",
  "natural glute ham raise": "bodyweight",
  "neck press": "barbell",
  "oblique crunches": "bodyweight",
  "oblique crunches - on the floor": "bodyweight",
  "olympic squat": "barbell",
  "one-arm dumbbell row": "dumbbell",
  "one-arm flat bench dumbbell flye": "dumbbell",
  "one-arm high-pulley cable side bends": "cable",
  "one-arm incline lateral raise": "dumbbell",
  "one-arm long bar row": "barbell",
  "one-arm side deadlift": "barbell",
  "one-arm side laterals": "dumbbell",
  "one-legged cable kickback": "cable",
  "one arm dumbbell bench press": "dumbbell",
  "one arm dumbbell preacher curl": "dumbbell",
  "one arm floor press": "barbell",
  "one arm lat pulldown": "cable",
  "one arm pronated dumbbell triceps extension": "dumbbell",
  "one arm supinated dumbbell triceps extension": "dumbbell",
  "one leg barbell squat": "barbell",
  "overhead cable curl": "cable",
  "overhead squat": "barbell",
  "pallof press": "cable",
  "pallof press with rotation": "cable",
  "palms-down dumbbell wrist curl over a bench": "dumbbell",
  "palms-down wrist curl over a bench": "barbell",
  "palms-up barbell wrist curl over a bench": "barbell",
  "palms-up dumbbell wrist curl over a bench": "dumbbell",
  "pin presses": "barbell",
  "plank": "bodyweight",
  "plie dumbbell squat": "dumbbell",
  "plyo push-up": "bodyweight",
  "power clean from blocks": "barbell",
  "power jerk": "barbell",
  "power partials": "dumbbell",
  "power snatch": "barbell",
  "power snatch from blocks": "barbell",
  "preacher curl": "barbell",
  "preacher hammer dumbbell curl": "dumbbell",
  "press sit-up": "barbell",
  "pull through": "cable",
  "pullups": "bodyweight",
  "push-up wide": "bodyweight",
  "push-ups - close triceps position": "bodyweight",
  "push-ups with feet elevated": "bodyweight",
  "push press": "barbell",
  "push press - behind the neck": "barbell",
  "push up to side plank": "bodyweight",
  "pushups": "bodyweight",
  "pushups (close and wide hand positions)": "bodyweight",
  "rack delivery": "barbell",
  "rack pull with bands": "barbell",
  "rack pulls": "barbell",
  "reverse band bench press": "barbell",
  "reverse band box squat": "barbell",
  "reverse band deadlift": "barbell",
  "reverse band power squat": "barbell",
  "reverse band sumo deadlift": "barbell",
  "reverse barbell curl": "barbell",
  "reverse barbell preacher curls": "barbell",
  "reverse cable curl": "cable",
  "reverse crunch": "bodyweight",
  "reverse flyes": "dumbbell",
  "reverse flyes with external rotation": "dumbbell",
  "reverse grip bent-over rows": "barbell",
  "reverse grip triceps pushdown": "cable",
  "reverse hyperextension": "machine",
  "reverse machine flyes": "machine",
  "reverse triceps bench press": "barbell",
  "rocket jump": "bodyweight",
  "rocking standing calf raise": "barbell",
  "romanian deadlift from deficit": "barbell",
  "rope crunch": "cable",
  "rope straight-arm pulldown": "cable",
  "russian twist": "bodyweight",
  "scissors jump": "bodyweight",
  "seated barbell military press": "barbell",
  "seated barbell twist": "barbell",
  "seated bent-over one-arm dumbbell triceps extension": "dumbbell",
  "seated bent-over rear delt raise": "dumbbell",
  "seated bent-over two-arm dumbbell triceps extension": "dumbbell",
  "seated cable rows": "cable",
  "seated cable shoulder press": "cable",
  "seated close-grip concentration barbell curl": "barbell",
  "seated dumbbell curl": "dumbbell",
  "seated dumbbell inner biceps curl": "dumbbell",
  "seated dumbbell palms-down wrist curl": "dumbbell",
  "seated dumbbell palms-up wrist curl": "dumbbell",
  "seated dumbbell press": "dumbbell",
  "seated flat bench leg pull-in": "bodyweight",
  "seated good mornings": "barbell",
  "seated leg tucks": "bodyweight",
  "seated one-arm dumbbell palms-down wrist curl": "dumbbell",
  "seated one-arm dumbbell palms-up wrist curl": "dumbbell",
  "seated one-arm cable pulley rows": "cable",
  "seated palm-up barbell wrist curl": "barbell",
  "seated palms-down barbell wrist curl": "barbell",
  "seated side lateral raise": "dumbbell",
  "seated triceps press": "dumbbell",
  "seated two-arm palms-up low-pulley wrist curl": "cable",
  "see-saw press (alternating side press)": "dumbbell",
  "shotgun row": "cable",
  "side bridge": "bodyweight",
  "side jackknife": "bodyweight",
  "side lateral raise": "dumbbell",
  "side laterals to front raise": "dumbbell",
  "single-arm cable crossover": "cable",
  "single-arm linear jammer": "barbell",
  "single-arm push-up": "bodyweight",
  "single-leg leg extension": "machine",
  "single dumbbell raise": "dumbbell",
  "single leg butt kick": "bodyweight",
  "single leg glute bridge": "bodyweight",
  "sit-up": "bodyweight",
  "smith incline shoulder raise": "barbell",
  "smith machine behind the back shrug": "machine",
  "smith machine bench press": "machine",
  "smith machine bent over row": "machine",
  "smith machine calf raise": "machine",
  "smith machine close-grip bench press": "machine",
  "smith machine decline press": "machine",
  "smith machine hang power clean": "machine",
  "smith machine hip raise": "machine",
  "smith machine incline bench press": "machine",
  "smith machine leg press": "machine",
  "smith machine one-arm upright row": "machine",
  "smith machine overhead shoulder press": "machine",
  "smith machine pistol squat": "machine",
  "smith machine reverse calf raises": "machine",
  "smith machine squat": "machine",
  "smith machine stiff-legged deadlift": "machine",
  "smith machine upright row": "machine",
  "smith single-leg split squat": "machine",
  "snatch": "barbell",
  "snatch balance": "barbell",
  "snatch deadlift": "barbell",
  "snatch pull": "barbell",
  "snatch shrug": "barbell",
  "snatch from blocks": "barbell",
  "speed box squat": "barbell",
  "speed squats": "barbell",
  "spell caster": "dumbbell",
  "spider crawl": "bodyweight",
  "spider curl": "barbell",
  "split clean": "barbell",
  "split jerk": "barbell",
  "split jump": "bodyweight",
  "split snatch": "barbell",
  "split squat with dumbbells": "dumbbell",
  "squat jerk": "barbell",
  "squat with bands": "barbell",
  "squat with chains": "barbell",
  "squat with plate movers": "barbell",
  "standing alternating dumbbell press": "dumbbell",
  "standing barbell calf raise": "barbell",
  "standing barbell press behind neck": "barbell",
  "standing bent-over one-arm dumbbell triceps extension": "dumbbell",
  "standing bent-over two-arm dumbbell triceps extension": "dumbbell",
  "standing biceps cable curl": "cable",
  "standing bradford press": "barbell",
  "standing cable chest press": "cable",
  "standing cable lift": "cable",
  "standing cable wood chop": "cable",
  "standing calf raises": "machine",
  "standing concentration curl": "dumbbell",
  "standing dumbbell calf raise": "dumbbell",
  "standing dumbbell press": "dumbbell",
  "standing dumbbell reverse curl": "dumbbell",
  "standing dumbbell straight-arm front delt raise above head": "dumbbell",
  "standing dumbbell triceps extension": "dumbbell",
  "standing dumbbell upright row": "dumbbell",
  "standing front barbell raise over head": "barbell",
  "standing inner-biceps curl": "dumbbell",
  "standing leg curl": "machine",
  "standing long jump": "bodyweight",
  "standing low-pulley deltoid raise": "cable",
  "standing low-pulley one-arm triceps extension": "cable",
  "standing military press": "barbell",
  "standing one-arm cable curl": "cable",
  "standing one-arm dumbbell curl over incline bench": "dumbbell",
  "standing one-arm dumbbell triceps extension": "dumbbell",
  "standing overhead barbell triceps extension": "barbell",
  "standing palm-in one-arm dumbbell press": "dumbbell",
  "standing palms-in dumbbell press": "dumbbell",
  "standing palms-up barbell behind the back wrist curl": "barbell",
  "standing rope crunch": "cable",
  "standing towel triceps extension": "bodyweight",
  "star jump": "bodyweight",
  "step-up with knee raise": "bodyweight",
  "stiff-legged barbell deadlift": "barbell",
  "stiff-legged dumbbell deadlift": "dumbbell",
  "stiff leg barbell good morning": "barbell",
  "straight-arm dumbbell pullover": "dumbbell",
  "straight-arm pulldown": "cable",
  "straight bar bench mid rows": "barbell",
  "straight raises on incline bench": "barbell",
  "sumo deadlift with bands": "barbell",
  "sumo deadlift with chains": "barbell",
  "t-bar row with handle": "barbell",
  "tate press": "dumbbell",
  "thigh abductor": "machine",
  "thigh adductor": "machine",
  "tricep dumbbell kickback": "dumbbell",
  "triceps overhead extension with rope": "cable",
  "triceps pushdown - rope attachment": "cable",
  "triceps pushdown - v-bar attachment": "cable",
  "tuck crunch": "bodyweight",
  "two-arm dumbbell preacher curl": "dumbbell",
  "underhand cable pulldowns": "cable",
  "upright barbell row": "barbell",
  "upright cable row": "cable",
  "v-bar pulldown": "cable",
  "v-bar pullup": "bodyweight",
  "vertical swing": "dumbbell",
  "weighted jump squat": "barbell",
  "weighted sissy squat": "barbell",
  "wide-grip barbell bench press": "barbell",
  "wide-grip decline barbell bench press": "barbell",
  "wide-grip decline barbell pullover": "barbell",
  "wide-grip lat pulldown": "cable",
  "wide-grip pulldown behind the neck": "cable",
  "wide-grip rear pull-up": "bodyweight",
  "wide-grip standing barbell curl": "barbell",
  "wide stance barbell squat": "barbell",
  "wide stance stiff legs": "barbell",
  "wind sprints": "bodyweight",
  "wrist rotations with straight bar": "barbell",
  "zercher squats": "barbell",
  "zottman curl": "dumbbell",
  "zottman preacher curl": "dumbbell",
};
